version: '3'
services:
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./docker-pg-init-scripts:/docker-entrypoint-initdb.d
# if you want to save pg data
#      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  postgres-client:
    container_name: 'postgres-client'
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dominique@example.com"
      PGADMIN_DEFAULT_PASSWORD: "dominique"
    ports:
      - "16543:80"
    depends_on:
      - postgres
  redis:
    container_name: 'redis'
    image: redis
    command: redis-server --requirepass root
    restart: always
# if you want to save redis data
#    volumes:
#      - ./redis-data:/data
    ports:
      - "6380:6379"
  redis-client:
    container_name: 'redis-client'
    image: erikdubbelboer/phpredisadmin
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=root
      
    restart: always
    depends_on:
      - redis
    ports:
      - "8081:80"
  backend:
    image: 'rate-limit-server'
    container_name: 'rate-limit-server'
    build: ./
    # replace original .env file defined value
    environment:
      ENV_MODE: 'dev'
      DB_HOST: postgres
      REDIS_ENDPOINT: redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_URI: postgres://postgres:root@postgres:5432/test_db
      JWT_SECRET_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis